### ISSUE TITLE
Changing window title 

### ISSUE THREAD

**Issue by Condzi** [fallahn/xygine#13]
Please,
Add possibility to change game window title using video settings in xy::App.

**Comment by fallahn** [comment]
Looking at this I've decided making the window title part of the video settings is probably not the right way to go about it. If the settings globally override any other window titling - for instance you may want to change the title per state (see the example application) then it becomes inflexible. On the other hand if you wish to use more than one window title... which do you store in the VideoSettings? Personally I prefer to keep it as is - the title can be changed at any time, by any state, using `getContext().renderWindow.setTitle()`
