### ISSUE TITLE
Stop escape key quitting game in debug

### ISSUE THREAD

**Issue by JonnyPtn** [fallahn/xygine#23]
It was super useful in the really early stages, but now I want to use escape for my pause key, it means the game quits whenever I try and pause in debug.

I'd propose one of:

1. Change the key to something less likely to clash, or add a modifier (e.g. shift + escape)
2. Remove the key and replace with a "quit" option in the debug menu
3. Modify the xy::app::handleEvent function to return a bool whether the event has been processed or not, so the engine can ignore key presses which are consumed by the game

**Comment by fallahn** [comment]
I think I'm going to just remove this. If someone wants escape to quit, then it's up to them to implement it, not the framework.
