### ISSUE TITLE
Issue with Box2D collisions not aligning

### ISSUE THREAD

**Issue by pmauldin** [fallahn/xygine#26]
Hi there!

I'm using Box2D to implement the collision in my game, and so far it's going great! (As an aside, I was able to use the xygine framework and integrate it with the Tiled ["Tile Collision Editor"](http://doc.mapeditor.org/reference/tmx-changelog/#tiled-010), so that collision bodies are automatically generated from the Tilesets internal object groups)

I'm having a slight issue now where the collision seems to be off by a few pixels and I can't seem to figure out why. When I use the debug drawing of the physics world, it doesn't seem like there should be any collisions. Any help is appreciated!

In the screenshots below, the cyan box is a Dynamic Rigidbody (controlled by keyboard input), and the rest are static bodies.

![collisionissue2](https://cloud.githubusercontent.com/assets/7992640/25312420/f5014698-27dd-11e7-8d08-8e63aebe408e.png)
![collisionissue](https://cloud.githubusercontent.com/assets/7992640/25312423/fcb1c052-27dd-11e7-90c6-28b8b72b73fe.png)

**Comment by fallahn** [comment]
Hi! When you say integrate with the Tiled Collision Editor I'm not sure I follow, I assume you mean xygine's [built in](https://github.com/fallahn/xygine/blob/master/xygine/include/xygine/tilemap/Map.hpp#L204) functions for creating physics bodies from a map? The effect you're seeing here is actually a 'feature' of Box2D, which is explained on page 17 of [the manual](http://box2d.org/manual.pdf) - unfortunately I can't link the page directly as it's a pdf.

**Comment by pmauldin** [comment]
No, I'm not using the built in functions, as those require an Object Layer. The way Tiled's Collision Editor works is it embeds the collision data within the Tile Layer, in an object group. You can see it [here ](https://github.com/pmauldin/Shift/blob/master/Shift/assets/maps/level.json )starting at line 32. [Here's the code](https://github.com/pmauldin/Shift/blob/master/Shift/src/states/GameState.cpp#L191) where I implemented this if you're curious.

As for the polygon skin, that does seem to explain what I'm seeing. So the recommendation is to just make the CollisionShape slightly smaller than the drawable?

Thanks for the help!

**Comment by pmauldin** [comment]
Reducing the size of my collision shapes worked great. Thanks!

**Comment by fallahn** [comment]
Good to hear! Any reason you use json particularly? If it's popular I'd consider adding support for it directly. As for the collision data if it's just an object group then it shouldn't be hard to extend support for that too... ObjectLayers are basically tmx object groups anyway.

**Comment by pmauldin** [comment]
Hey, sorry, didn't get this notification for some reason! Just happened to see your comment. I'm not actually using the JSON in my code, I just export it as JSON as well because I find it more human-readable that way when I'm trying to view the structure of the exported map, if that makes sense.

**Comment by fallahn** [comment]
No problem! I believe you get automatically unsubscribed when an issue is closed. Anyway, thanks for the answer,  I'm always looking out for ways to make improvements.
