### ISSUE TITLE
xy::Camera::setZoom is misleading

### ISSUE THREAD

**Issue by JonnyPtn** [fallahn/xygine#27]
The zoom is relative, e.g. if you set the zoom to 1.1 every frame, it will continuously zoom in.

I'd propose either renaming the function to just "xy::Camera::zoom()", or changing the functionality so the zoom is absolute.

example: https://github.com/JonnyPtn/xyworld/blob/master/src/WorldState.cpp#L120

**Comment by fallahn** [comment]
fixed! Thanks
