### ISSUE TITLE
Cannot find enet members

### ISSUE THREAD

**Issue by fallahn** [fallahn/xygine#43]
Moved from [here](https://github.com/fallahn/xygine/issues/21#issuecomment-346566443):

I took the latest master build of xygine and getting this error..

```
/Users/Projects/xygine/xyginext/src/network/NetHost.cpp:128:21: error: no member named 'connectedPeers' in
'_ENetHost'
if (m_host->connectedPeers > 0)
~~~~~~ ^
/Users/Projects/xygine/xyginext/src/network/NetHost.cpp:130:43: error: no member named 'connectedPeers' in
'_ENetHost'
for (auto i = 0u; i < m_host->connectedPeers; ++i)
~~~~~~ ^
/Users/Projects/xygine/xyginext/src/network/NetHost.cpp:213:31: error: no member named 'connectedPeers' in
'_ENetHost'
return (m_host) ? m_host->connectedPeers : 0;
~~~~~~ ^
3 errors generated.
make[2]: *** [CMakeFiles/xyginext.dir/src/network/NetHost.cpp.o] Error 1
make[1]: *** [CMakeFiles/xyginext.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by fallahn** [comment]
Sounds like enet is not properly installed. Try installing it via homebrew, which works with the [travis builds](https://travis-ci.org/fallahn/xygine/jobs/305469861#L49) for xcode 6  through 9

**Comment by Clever-Boy** [comment]
Tried installing through brew.  The build files get generated w/o any errors but same error as above during make.  Xcode version (Version 9.0.1 (9A1004))

==== Build==== 

-- The C compiler identification is AppleClang 9.0.0.9000038
-- The CXX compiler identification is AppleClang 9.0.0.9000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SFML .. in /Library/Frameworks/SFML.framework
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework  
-- Found ENet: /usr/local/lib/libenet.dylib  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Projects/xygine/build

**Comment by fallahn** [comment]
@JonnyPtn any ideas?

**Comment by JonnyPtn** [comment]
I use an almost identical environment here - Brew is usually decent at keeping things up to date, but can you just confirm you have enet version 1.3.13? (You can check with `brew list --versions`)

**Comment by Clever-Boy** [comment]
Not sure why I am getting this error. Version is the same 

$ brew list --versions
coreutils 8.25
ctags 5.8_1
enet 1.3.13

**Comment by Clever-Boy** [comment]
Sorry my error. I had another project that used enet and it used the older header files. I pointed to the latest version and it was all good. Again sorry to take your time. Was wondering do i need to build anything further with the files in cmake template folder..

**Comment by fallahn** [comment]
No problem, sorry I couldn't be more help, I don't have much experience with macOS (@JonnyPtn is the man :) ). The cmake template folder is used for creating projects which link to xygine. The demo folder has a cmake file in it which should better show how it works. Generally you copy the template to a new directory, edit the cmake file with your project name, and then add source files to the cmakelists.txt file in the template/src directory.
