### ISSUE TITLE
Expose ImGui theme settings via ConfigFile

### ISSUE THREAD

**Issue by fallahn** [fallahn/xygine#60]
It might be nice when integrating the ImGui classes with your own game to be able to more easily customise the appearance. As ImGui uses pretty simple theme settings I thought it might be nice to expose these via something like `xy::Nim::loadTheme(const std::string& pathToConfig)` where the config file contains a list of values (float - vec4 are currently supported) which can be mapped to various style properties. This way custom themes can be loaded at run time (and possibly included in the editor, hint hint ;) )

**Comment by JonnyPtn** [comment]
I like this idea, I'm currently using the ImGui demo style editor which should save, but doesn't work for me :( May be some code worth using there though
