### ISSUE TITLE
Change resolution

### ISSUE THREAD

**Issue by zerodarkzone** [fallahn/xygine#63]
Hi,
It looks like the default internal resolution is 1920X1080 and I haven't been able to change it. If I change the renderWindow size it just resizes de window and everything inside it, if I try to change the contex view, then it doesn't render everything in the screen. So how can I change this resolution?.
Thanks

**Comment by fallahn** [comment]
I've not tried it but you can probably just change this value and recompile the library:
https://github.com/fallahn/xygine/blob/master/xyginext/include/xyginext/Config.hpp#L71

Normally you can change the resolution of the window by using the video options (press F1 when the game is running) but if you want to show more or less of the game area you can also change the zoom level of the scene's active camera, or set the camera's view explicitly:
https://github.com/fallahn/xygine/blob/master/xyginext/include/xyginext/ecs/components/Camera.hpp#L57

**Comment by zerodarkzone** [comment]
Thanks,
I was able to solve it by changing the view of the camera. But it was also necessary to reposition the camera. I don't know if it would be better to center the camera when you change the view.

**Comment by fallahn** [comment]
OK good to know. I'll consider automatically updating the position - but I don't like to assume the end user's use case. If you only set the view once then updating the position at the same time shouldn't be too great an onus :)
