### ISSUE TITLE
Add set framerate limit to video options

### ISSUE THREAD

**Issue by fallahn** [fallahn/xygine#72]
In order to address using max CPU when xy windows lose focus this should be added next to the v-sync button in the options menu (along with some value box to set the max frame rate?). Probably needs to auto-uncheck the v-sync button when selected and vice versa to prevent both being enabled at once.

**Comment by JonnyPtn** [comment]
As far as I can tell this is implemented and working so can be closed?

**Comment by fallahn** [comment]
pretty much - although istr there was an issue switching it between vsync/framelimit which I meant to come back to so I left this open (silly me didn't implement this in its own branch)

**Comment by JonnyPtn** [comment]
I think that's the issue I fixed with #74. The symptoms were that it would set the frame rate once, and then toggle between sync and frameratelimit nicely, but trying to subsequently change the frameratelimit would have no effect

**Comment by fallahn** [comment]
Ah yes, that sounds about right. Good stuff!
