### ISSUE TITLE
Don't use system include paths when including xyginext headers

### ISSUE THREAD

**Issue by JonnyPtn** [fallahn/xygine#80]
Minor issue I've had for a while - xyginext source files include xyginext headers using '#include <*.hpp>' instead of '#include "*"' which means when I'm working on xyginext itself, it includes the installed headers (which will almost always be out of date) instead of the project ones, so I have to clear out my /usr/local/include/xyginext folder whenever I make changes to the xyginext headers

Like I said, it's not a huge issue, but if it has no other negative effects (which I don't believe it should?) then it would be a helpful change. I can easily roll it into the other changes I'm making for the editor if you don't have any objections?

**Comment by fallahn** [comment]
Oh! This explains some problems I had on linux... yeah go for it. If you can make this a separate PR (or prefer that I do it) then I can update it sooner rather than later

**Comment by JonnyPtn** [comment]
Once I've worked out the regex magic needed for the find & replace I'll stick it in a separate PR
