### ISSUE TITLE
Check if an entity is valid

### ISSUE THREAD

**Issue by zerodarkzone** [fallahn/xygine#83]
Hi,
is there a way to check if an entity is in a valid state?

**Comment by fallahn** [comment]
Broadly, no, not at the moment. You can check `entity.hasComponent<T>()` to see if an entity is as you expect, or `entity.destroyed()`to see if it's marked for destruction on the next update, but other than that there's no specific function. It can probably be added, depending on your definition of 'valid'. For example creating an entity by any means other than `Scene::createEntity()` will create one without a valid entity manager pointer. If this is the check you need I'll happily add a function for it.

**Comment by zerodarkzone** [comment]
Thanks

**Comment by fallahn** [comment]
Feedback is always appreciated, thanks for giving xygine a try!
