### ISSUE TITLE
xy::Util::Vector::normalise fails assertion on 0 length vectors

### ISSUE THREAD

**Issue by JonnyPtn** [fallahn/xygine#99]
calling `xy::Util::Vector::normalise(vec)` where `vec` is 0,0 causes an assert to fail. I'd expect it to just return 0,0?

Not a major issue, as I can adjust my code to handle these special cases, just seems like it would add some convenience without any downsides?

**Comment by fallahn** [comment]
Originally I believe I returned a zero vector, but changed the behaviour based on a post on the sfml forum - possibly [this one](https://en.sfml-dev.org/forums/index.php?topic=12603.msg88360#msg88360) which seemed to make more sense to me, ie the fact that you're trying to normalise a zero vector implies a logic error.

**Comment by JonnyPtn** [comment]
Seems reasonable, the length should always be 1. Thanks!
